config/routes.rb
V1::Application.routes.draw do

  devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'create_new_splitter' }
  root :to => 'announcements#index'
  
  resources :cms
  resources :works
  resources :placements, :controller=>"works"
  resources :news, :controller=>"announcements"
  resources :announcements
  resources :artists
  resources :releases, :controller=>"sounds"
  resources :sounds
  resources :clients
  resources :socials
  
  get "/get_announcement_links" => "announcements#create_links", :as => :get_announcement_links
  get "/get_work_links" => "works#create_links", :as => :get_work_links
  get "/get_artist_links" => "artists#create_links", :as => :get_artist_links
  get "/get_sound_links" => "sounds#create_links", :as => :get_sound_links
  
  resources :abouts, :path => "about"
  resources :contacts, :path => "contact"
  
  get '*path' => redirect('/')
  
end

app/controllers/cms_controller.rb
class CmsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    bring_in_models
  end
  
end

app/helpers/cms_helper.rb
module CmsHelper
end

app/views/cms/_abouts.html.erb
<div class="cmsWrapper">
	<div class="releases">
		<div class="divHeader">Contact details</div>
		<div class="tableWrapper">
			<div class="tableContent">
				<% if @abouts.count > 0 %>
					<table width="100%">
						<tr class="tableHeader">
							<th>CONTACT EMAIL ADDRESS</th>
						</tr>
						<tr><hr class="ruler"/></tr>
						<% @abouts.each do |a| %>
							<tr class="tableRow">
								<td width="97%"><%= a.email %></td>
								<td width="2%" class="topperButtons"><%= link_to "edit", edit_about_path(a), :title => "Edit about copy", :class => "btn btn2 tips" %></td>
								<% if @user.email != @testing %>
									<td width="1%" class="topperButtons"><%= button_to "X", a, :method => :delete, :class => "btn btn3 delete_post", :remote => true %></td>
								<% end %>
							</tr>
						<% end %>
					</table>
				<% else %>
					<table width="100%">
						<tr class="tableRow empty">
							<td>
								<em>YOU HAVE NO CONTACT DETAILS IN PLACE YET... ADD SOME BELOW ?!</em>
							</td>
						</tr>
					</table>
				<% end %>
			</div>
		</div>
	</div>
	<% if @abouts.count < 1 %>
		<h6>
			<input type="hidden" value="works" class="modal-model-type">
		<h6><%= link_to 'Add about copy', new_about_path, :class => "darkButton2" %></h6>
	<% end %>
</div>

app/views/cms/_announcements.html.erb
<div class="cmsWrapper">
	<div class="releases">
		<div class="divHeader">News items</div>
		<div class="tableWrapper">
			<div class="tableContent">
				<% if @announcements.count > 0 %>
					<table width="100%">
						<tr class="tableHeader">
							<th>TITLE</th>
							<th>DESCRIPTION</th>
							<th>VIMEO</th>
							<th>S'CLOUD</th>
							<th>FB IMAGE</th>
						</tr>
						<tr><hr class="ruler"/></tr>
						<% @announcements.each do |a| %>
							<tr class="tableRow">
								<td width="26%"><%= truncate(a.homepage_title, :length => 22) %></td>
								<td width="41%"><%= truncate(a.description, :length => 45) %></td>
								<td width="9%"><%= a.vimeo %></td>
								<td width="11%"><%= a.soundcloud %></td>
								<% if a.facebook_image == '' || a.facebook_image.blank? %>
									<td width="10%" class="topperButtons">NO</td>
								<% else %>
									<td width="10%" class="topperButtons">YES</td>
								<% end %>
								<td width="1%" class="topperButtons"><%= link_to "E", edit_announcement_path(a), :title => "Edit announcement", :class => "btn btn2 tips" %></td>
								<% if @user.email != @testing %>
									<td width="1%" class="topperButtons"><%= button_to "X", a, :method => :delete, :class => "btn btn3 delete_post", :remote => true %></td>
								<% end %>
							</tr>
						<% end %>
					</table>
				<% else %>
					<table width="100%">
						<tr class="tableRow empty">
							<td>
								<em>YOU HAVE NO NEWS ITEMS YET... ADD SOME BELOW ?!</em>
							</td>
						</tr>
					</table>
				<% end %>
			</div>
		</div>
	</div>
	<h6>
	<input type="hidden" value="works" class="modal-model-type">
	<h6><%= link_to 'Add news item', new_announcement_path, :class => "darkButton2" %></h6>
</div>

app/views/cms/_artists.html.erb
<div class="cmsWrapper">
	<div class="releases">
		<div class="divHeader">Artists</div>
		<div class="tableWrapper">
			<div class="tableContent">
				<% if @artists.count > 0 %>
					<table width="100%">
						<tr class="tableHeader">
							<th>NAME</th>
							<th>INFO</th>
							<th>LATEST</th>
							<th>HOME</th>
							<th>S'CLOUD</th>
							<th>FB IMAGE</th>
							<th>FB URL</th>
							<th>TWIT. URL</th>
						</tr>
						<tr><hr class="ruler"/></tr>
						<% @artists.each do |a| %>
							<tr class="tableRow">
								<td width="20%"><%= truncate(a.name, :length => 20) %></td>
								<td width="26%"><%= truncate(a.description, :length => 26) %></td>
								<td width="7%"><%= a.latest %></td>
								<td width="7%"><% if a.homepage == true %><%= "true" %><% else %><%= "false" %><% end %></td>
								<td width="13%"><%= a.soundcloud %></td>
								<% if a.facebook_image == '' || a.facebook_image.blank? %>
									<td width="8%" class="topperButtons">NO</td>
								<% else %>
									<td width="8%" class="topperButtons">YES</td>
								<% end %>
								<% if a.fb_url == '' || a.fb_url.blank? %>
									<td width="8%" class="topperButtons">NO</td>
								<% else %>
									<td width="8%" class="topperButtons">YES</td>
								<% end %>
								<% if a.twitter_name == '' || a.twitter_name.blank? %>
									<td width="8%" class="topperButtons">NO</td>
								<% else %>
									<td width="8%" class="topperButtons">YES</td>
								<% end %>
								<td width="1%" class="topperButtons"><%= link_to "E", edit_artist_path(a), :title => "Edit #{a.name}",:class => "btn btn2 tips" %></td>
								<% if @user.email != @testing %>
									<td width="1%" class="topperButtons"><%= button_to "X", a, :method => :delete, :class => "btn btn3 delete_post", :remote => true %></td>
								<% end %>
							</tr>
						<% end %>
					</table>
				<% else %>
					<table width="100%">
						<tr class="tableRow empty">
							<td>
								<em>YOU HAVE NO ARTIST YET... ADD SOME BELOW ?!</em>
							</td>
						</tr>
					</table>
				<% end %>
			</div>
		</div>
	</div>
	<h6>
	<input type="hidden" value="works" class="modal-model-type">
	<h6><%= link_to 'Add artist', new_artist_path, :class => "darkButton2" %></h6>
</div>

app/views/cms/_clients.html.erb
<div class="cmsWrapper">
	<div class="releases">
		<div class="divHeader">Clients</div>
		<div class="tableWrapper">
			<div class="tableContent">
				<% if @clients.count > 0 %>
					<table width="100%">
						<tr class="tableHeader">
							<th>NAME</th>
							<th>CLIENT WEBSITE URL</th>
							<th>IMAGE?</th>
						</tr>
						<tr><hr class="ruler"/></tr>
						<% @clients.each do |c| %>
							<tr class="tableRow">
								<td width="46%"><%= truncate(c.name, :length => 42) %></td>
								<td width="40%"><%= c.url %></td>
								<td width="12%"><% if c.image.present? %><%= "yes" %><% else %><%= "no" %><% end %></td>
								<td width="1%" class="topperButtons"><%= link_to "E", edit_client_path(c), :title => "Edit #{c.name}",:class => "btn btn2 tips" %></td>
								<% if @user.email != @testing %>
									<td width="1%" class="topperButtons"><%= button_to "X", c, :method => :delete, :class => "btn btn3 delete_post", :remote => true %></td>
								<% end %>
							</tr>
						<% end %>
					</table>
				<% else %>
					<table width="100%">
						<tr class="tableRow empty">
							<td>
								<em>YOU HAVE NO CLIENTS YET... ADD SOME BELOW ?!</em>
							</td>
						</tr>
					</table>
				<% end %>
			</div>
		</div>
	</div>
	<h6>
	<input type="hidden" value="works" class="modal-model-type">
	<h6><%= link_to 'Add client', new_client_path, :class => "darkButton2" %></h6>
</div>

app/views/cms/_socials.html.erb
<div class="cmsWrapper">
	<div class="releases">
		<div class="divHeader">Social network images (for site index pages)</div>
		<div class="tableWrapper">
			<div class="tableContent">
				<% if @socialconts.count > 0 %>
					<table width="100%">
						<tr class="tableHeader">
							<th>CATEGORY</th>
							<th>IMAGE PRESENT?</th>
							<th>IMAGE NAME</th>
						</tr>
						<tr><hr class="ruler"/></tr>
						<% @socialconts.each do |s| %>
							<tr class="tableRow">
								<td width="15%">NEWS</td>
								<td width="30%">
									<% if s.announcements_image? %>YES<% else %>NO<% end %>
								</td>
								<td width="55%">
									<% if s.announcements_image? %>
										<%= s.announcements_image_file_name %>
									<% else %>
										"N/A"
									<% end %>
								</td>
							</tr>
							<tr class="tableRow">
								<td width="15%">WORKS</td>
								<td width="30%">
									<% if s.works_image? %>YES<% else %>NO<% end %>
								</td>
								<td width="55%">
									<% if s.works_image? %>
										<%= s.works_image_file_name %>
									<% else %>
										"N/A"
									<% end %>
								</td>
							</tr>
							<tr class="tableRow">
								<td width="15%">ARTISTS</td>
								<td width="30%">
									<% if s.artists_image? %>YES<% else %>NO<% end %>
								</td>
								<td width="55%">
									<% if s.artists_image? %>
										<%= s.artists_image_file_name %>
									<% else %>
										"N/A"
									<% end %>
								</td>
							</tr>
							<tr class="tableRow">
								<td width="15%">PLAYLISTS</td>
								<td width="30%">
									<% if s.playlists_image? %>YES<% else %>NO<% end %>
								</td>
								<td width="55%">
									<% if s.playlists_image? %>
										<%= s.playlists_image_file_name %>
									<% else %>
										"N/A"
									<% end %>
								</td>
							</tr>
							<tr class="tableRow">
								<td width="15%">ABOUT</td>
								<td width="30%">
									<% if s.abouts_image? %>YES<% else %>NO<% end %>
								</td>
								<td width="55%">
									<% if s.abouts_image? %>
										<%= s.abouts_image_file_name %>
									<% else %>
										"N/A"
									<% end %>
								</td>
							</tr>
							<tr class="tableRow">
								<td width="15%">CONTACT</td>
								<td width="30%">
									<% if s.contacts_image? %>YES<% else %>NO<% end %>
								</td>
								<td width="55%">
									<% if s.contacts_image? %>
										<%= s.contacts_image_file_name %>
									<% else %>
										"N/A"
									<% end %>
								</td>
							</tr>
							<tr class="tableRow topperMargin2">
								<td width="15%" class="topperButtons"><%= link_to "Edit social images", edit_socialcont_path(s), :title => "Edit social images",:class => "btn btn2 tips" %></td>
								<% if @user.email != @testing %>
									<td width="30%" class="topperButtons"><%= button_to "Delete social images", s, :method => :delete, :class => "btn btn3 delete_post", :remote => true %></td>
								<% end %>
							</tr>
						<% end %>
					</table>
				<% else %>
					<table width="100%">
						<tr class="tableRow empty">
							<td>
								<em>YOU HAVE NO IMAGES YET... ADD THEM BELOW ?!</em>
							</td>
						</tr>
					</table>
				<% end %>
			</div>
		</div>
	</div>
	<h6>
	<input type="hidden" value="works" class="modal-model-type">
	<% if @socialconts.count < 1 %><h6><%= link_to 'Add social record', new_socialcont_path, :class => "darkButton2" %><% end %></h6>
</div>

app/views/cms/_sounds.html.erb
<div class="cmsWrapper">
	<div class="releases">
		<div class="divHeader">Releases</div>
		<div class="tableWrapper">
			<div class="tableContent">
				<% if @sounds.count > 0 %>
					<table width="100%">
						<tr class="tableHeader">
							<th>TITLE</th>
							<th>INFO</th>
							<th>S'CLOUD</th>
							<th>LATEST</th>
							<th>HOME</th>
							<th>FB IMAGE</th>
						</tr>
						<tr><hr class="ruler"/></tr>
						<% @sounds.each do |s| %>
							<tr class="tableRow">
								<td width="44%"><%= truncate(s.title, :length => 50) %></td>
								<% if s.description.blank? || s.description == '' %>
									<td width="10%">NO</td>
								<% else %>
									<td width="10%">YES</td>
								<% end %>
								<td width="12%"><%= s.soundcloud %></td>
								<td width="7%"><%= s.latest %></td>
								<td width="7%"><% if s.homepage == true %><%= "true" %><% else %><%= "false" %><% end %></td>
								<% if s.facebook_image == '' || s.facebook_image.blank? %>
									<td width="10%" class="topperButtons">NO</td>
								<% else %>
									<td width="10%" class="topperButtons">YES</td>
								<% end %>
								<td width="1%" class="topperButtons"><%= link_to "E", edit_release_path(s), :title => "Edit release - #{s.title}", :class => "btn btn2 tips" %></td>
								<% if @user.email != @testing %>
									<td width="1%" class="topperButtons"><%= button_to "X", s, :method => :delete, :class => "btn btn3 delete_post", :remote => true %></td>
								<% end %>
							</tr>
						<% end %>
					</table>
				<% else %>
					<table width="100%">
						<tr class="tableRow empty">
							<td>
								<em>YOU HAVE NO PLAYLISTS YET... ADD SOME BELOW ?!</em>
							</td>
						</tr>
					</table>
				<% end %>
			</div>
		</div>
	</div>
	<h6>
	<input type="hidden" value="works" class="modal-model-type">
	<h6><%= link_to 'Add new playlist', new_release_path, :class => "darkButton2" %></h6>
</div>

app/views/cms/_works.html.erb
<div class="cmsWrapper">
	<div class="releases">
		<div class="divHeader">Placements</div>
		<div class="tableWrapper">
			<div class="tableContent">
				<% if @works.count > 0 %>
					<table width="100%">
						<tr class="tableHeader">
							<th>TITLE</th>
							<th>CLIENT</th>
							<th>INFO</th>
							<th>VIMEO</th>
							<th>LATEST</th>
							<th>HOME</th>
							<th>ARTIST</th>
							<th>FB IMAGE</th>
						</tr>
						<tr><hr class="ruler"/></tr>
						<% @works.each do |work| %>
						<% artist_name = work.artist.name rescue "NONE" %>
							<tr class="tableRow">
								<td width="27%"><%= truncate(work.title, :length => 25) %></td>
								<td width="22%"><%= truncate(work.client, :length => 20) %></td>
								<% if work.description.blank? || work.description == '' %>
									<td width="6%">NO</td>
								<% else %>
									<td width="6%">YES</td>
								<% end %>
								<td width="8%"><%= work.vimeo %></td>
								<td width="6%"><%= work.latest %></td>
								<td width="6%"><% if work.homepage == true %><%= "true" %><% else %><%= "false" %><% end %></td>
								<td width="10%"><%= truncate(artist_name, :length => 11) %></td>
								<% if work.facebook_image == '' || work.facebook_image.blank? %>
									<td width="10%" class="topperButtons">NO</td>
								<% else %>
									<td width="10%" class="topperButtons">YES</td>
								<% end %>
								<td width="1%" class="topperButtons"></td>
								<td width="1%" class="topperButtons"><%= link_to "E", edit_placement_path(work), :title => "Edit #{work.title}", :class => "btn btn2 tips" %></td>
								<% if @user.email != @testing %>
									<td width="1%" class="topperButtons"><%= button_to "X", work, :method => :delete, :class => "btn btn3 delete_post", :remote => true %></td>		
								<% end %>
							</tr>
						<% end %>
					</table>
				<% else %>
					<table width="100%">
						<tr class="tableRow empty">
							<td>
								<em>YOU HAVE NO WORKS YET... ADD SOME BELOW ?!</em>
							</td>
						</tr>
					</table>
				<% end %>
			</div>
		</div>
	</div>
	<h6>
	<input type="hidden" value="works" class="modal-model-type">
	<h6><%= link_to 'Add new work', new_work_path, :class => "darkButton2" %></h6>
</div>

app/views/cms/index.html.erb
<div class="col-md-12">
	<div class="static">
		<div class="logo2"><%= link_to(image_tag('newLogo.jpg'), announcements_path) %></a></div>
		<div class="col-md-10 col-sm-offset-1 topper">
			<h1 class="formHeader">Edit your content below</h1>
			<hr class="projectSeparator" />
		</div>
	</div>
	<div class="col-md-10 col-sm-offset-1 topper">	
		<div class="fixerScroll bottom">
			<%= render partial: 'abouts' %>
			<%= render partial: 'announcements' %>
			<%= render partial: 'works' %>
			<%= render partial: 'artists' %>
			<%= render partial: 'sounds' %>
			<%#= render partial: 'clients' %>
			<%= render partial: 'socials' %>
		</div>
	</div>
</div>