config/routes.rb
V1::Application.routes.draw do

  devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'create_new_splitter' }
  root :to => 'announcements#index'
  
  resources :cms
  resources :works
  resources :placements, :controller=>"works"
  resources :news, :controller=>"announcements"
  resources :announcements
  resources :artists
  resources :releases, :controller=>"sounds"
  resources :sounds
  resources :clients
  resources :socials
  
  get "/get_announcement_links" => "announcements#create_links", :as => :get_announcement_links
  get "/get_work_links" => "works#create_links", :as => :get_work_links
  get "/get_artist_links" => "artists#create_links", :as => :get_artist_links
  get "/get_sound_links" => "sounds#create_links", :as => :get_sound_links
  
  resources :abouts, :path => "about"
  resources :contacts, :path => "contact"
  
  get '*path' => redirect('/')
  
end

app/views/layouts/_main.html.erb
<div class="col-md-8">
	<div class="rightSide">
		<div id="content">
				<div class="">
		    		<div id="container" class="clearfix">
						<div class="elementContainer clearfix announcements">
							<div class="rightHandSection2">
								<div>
									<%= yield %>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/layouts/_navigation.html.erb
<div class="col-md-4">
	<div class="leftSide">
		<% if user_signed_in? %>
			<div class="userInfo">
				<div>{ Logged in as <strong><%= current_user.email %></strong> }</div>
				<%= link_to 'Edit', edit_user_registration_path %> | 
				<%= link_to 'Logout', destroy_user_session_path, :method => :delete %> |
				<%= link_to 'CMS', cms_path %></div>
			</div>
		<% end %>
		<div class="logo"><%= link_to(image_tag('newLogo.jpg', class: "logo"), news_index_path) %></div>
		<div class="navigationWrapper">
			<ul id="menu" class="navigation option-set clearfix">
				<li class="navButton"><%= link_to 'Artists', artists_path, :class => "navigationButton" %></li>
				<li class="navButton"><%= link_to 'Releases', releases_path, :class => "navigationButton" %></li>
				<li class="navButton"><%= link_to 'Placements', placements_path, :class => "navigationButton" %></li>
				<!-- <li class="navButton"><%#= link_to 'About', abouts_path, :class => "navigationButton" %></li> -->
				<li class="navButton"><%= link_to 'Contact', contacts_path, :class => "navigationButton" %></li>
			</ul>
		</div>
		<div class="social">
			<div class="centerSocial">
				<a href="https://www.facebook.com/pages/Fairsplit-Music/609198105854352" target="_blank">
					<i class="fa fa-facebook fa-lg"></i>
				</a>
				<a href="https://twitter.com/FairsplitMusic" target="_blank">
					<i class="fa fa-twitter fa-lg"></i>
				</a>
				<a href="" target="_blank">
					<i class="fa fa-instagram fa-lg"></i>
				</a>
				<a href="https://www.youtube.com/channel/UCcjbocHGR4WaSlrkqSfbwBg" target="_blank">
					<i class="fa fa-youtube fa-lg"></i>
				</a>
				<a href="https://soundcloud.com/fairsplit-music" target="_blank">
					<i class="fa fa-soundcloud"></i>
				</a>
				<span class="pipe">|</span> 
				<a class="fixMute" href="#filter=.contact">
					<i class="fa fa-envelope-o fa-lg"></i>
				</a>
			</div>
		</div>
		<!--<div class="client"><a href="#filter=.client_login">Client Login</a></div>-->
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>Split Music | 21st Century Music Publishing | Unique Music to Picture</title>
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<meta name="description" content="Split Music | 21st Century Music Publishing | Unique Music to Picture | Our passion is diverse, authentic music. Our expertise is in applying it to picture. We choose writers that create vibrant textures and emotions, transcending beyond music into powerful, dynamic audio visual format.">
		<meta name="title" content="Split Music | 21st Century Music Publishing | Unique Music to Picture">
	  	
		<!-- Google Knowledge Graph - social profiles -->
		<script type="application/ld+json">
		{ "@context" : "http://schema.org",
		  "@type" : "Organization",
		  "name" : "Fairsplit Music",
		  "url" : "http://www.fairsplitmusic.com/",
		  "sameAs" : [
		     "https://www.facebook.com/fairsplitmusic",
		     "https://twitter.com/FairsplitMusic",
		     "https://instagram.com/fairsplitmusic",
		     "https://www.youtube.com/channel/UCk3ATtNUbTmgPLyTvadTMnw",
		     "https://www.linkedin.com/company/fairsplit-music-publishing"]
		}
		</script>
		
		<!-- Google Knowledge Graph - site name breadcrumb in SERPs -->
		<script type="application/ld+json">
		    {  "@context" : "http://schema.org",
		       "@type" : "WebSite",
		       "name" : "Fairsplit Music",
		       "alternateName" : "FairsplitMusic",
		       "url" : "http://www.fairsplitmusic.com/"
		    }
		</script>
		
		<!-- Google Knowledge Graph - company logo -->
		<script type="application/ld+json">
		   { "@context": "http://schema.org",
		      "@type": "Organization",
		      "url": "http://www.fairsplitmusic.com/",
		      "logo": "https://s3.amazonaws.com/fairsplit-images/fbLogo2.jpg"
		    }
		</script>
		
		<%= analytics_init if Rails.env.production? %>
		
		<%= stylesheet_link_tag    "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?sensor=true" %>
		<%= csrf_meta_tags %>
		<%= display_meta_tags %>
		
		<%= favicon_link_tag 'favicon.png' %>
		
		<link href='https://fonts.googleapis.com/css?family=Raleway:400,500,700|Open+Sans:300,700' rel='stylesheet' type='text/css'>
		
	</head>
	
	<body bgcolor="#000000">
	<!-- 		
			<div id="preloader">
				<%#= image_tag 'status2.gif', :id => "status" %>
			</div> -->
		
		<div id="contentHome">
		
			<% if controller_name == "abouts" && controller.action_name == "index" || 
			      controller_name == "contacts" && controller.action_name == "index" || 
				  controller_name == "announcements" && controller.action_name == "index" || 
				  controller_name == "announcements" && controller.action_name == "show" || 
				  controller_name == "artists" && controller.action_name == "index" || 
				  controller_name == "artists" && controller.action_name == "show" || 
				  controller_name == "sounds" && controller.action_name == "index" || 
				  controller_name == "sounds" && controller.action_name == "show" ||
				  controller_name == "works" && controller.action_name == "index" || 
				  controller_name == "works" && controller.action_name == "show" %> 
		
				<div class="navigation"><%= render 'layouts/navigation' %></div>
				<div class="main"><%= render 'layouts/main' %></div>
			
			<% else %>
		
				<%= yield %>
			
			<% end %>
			
		</div>
		
	</body>
	
</html>